backend:
  app_id: 'diemas'
  name: github
  repo: DiemasMichiels/diemas
  branch: main
  base_url: https://diemas.vercel.app
  auth_endpoint: api/auth/callback

media_folder: 'public/images'
public_folder: '/images'
logo_url: https://diemas.vercel.app/icon.svg

collections:
  - name: 'page'
    label: 'Pages'
    folder: 'content/pages'
    create: true
    slug: '{{fields.slug}}'
    summary: '{{fields.slug}} - {{fields.title}}'
    fields:
      - { label: 'slug', name: 'slug', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          required: false,
        }
      - {
          label: 'Subtitle',
          name: 'subtitle',
          widget: 'markdown',
          required: false,
        }
      - {
          label: 'Text',
          name: 'text',
          widget: 'markdown',
          options: { buttons: ['heading-one'] },
          required: false,
        }
